class PortFolioItem{
  String title;
  PortFolioItem({required this.title});
}

final languages = [
  PortFolioItem(title: "Flutter"),
  PortFolioItem(title: "ReactJs"),
  PortFolioItem(title: "HTML"),
  PortFolioItem(title: "CSS"),
  PortFolioItem(title: "Figma"),
  PortFolioItem(title: "Lunacy"),
  PortFolioItem(title: "Adobe After Effects"),
  PortFolioItem(title: "Adobe Photoshop"),
  PortFolioItem(title: "Cavalry"),
  PortFolioItem(title: "Blender"),
  PortFolioItem(title: "Javascript"),
  PortFolioItem(title: "JQuery"),
  PortFolioItem(title: "MongoDB"),
  PortFolioItem(title: "Redux"),
  PortFolioItem(title: "ReactNative"),
  PortFolioItem(title: "Github"),
  PortFolioItem(title: "Node.js"),
  PortFolioItem(title: "Java"),
  PortFolioItem(title: "Kotlin"),
  PortFolioItem(title: "Firebase"),
];

final interests = [
  PortFolioItem(title: "Frontend"),
  PortFolioItem(title: "Backend"),
  PortFolioItem(title: "Fullstack"),
  PortFolioItem(title: "UI/UX"),
  PortFolioItem(title: "Artificial Intelligence"),
  PortFolioItem(title: "CyberSecurity"),
  PortFolioItem(title: "Database"),
  PortFolioItem(title: "Internet"),
];

final skills = [
  PortFolioItem(title: "Android Development"),
  PortFolioItem(title: "Animation"),
  PortFolioItem(title: "Application Programming interface(API)"),
  PortFolioItem(title: "Basic Computer Maintenance"),
  PortFolioItem(title: "Coaching"),
  PortFolioItem(title: "Computer Aided Design (CAD)"),
  PortFolioItem(title: "Concepting and Ideation"),
  PortFolioItem(title: "Conflict and Complaint Resolution"),
  PortFolioItem(title: "Creative Design"),
  PortFolioItem(title: "Creative Thinking"),
  PortFolioItem(title: "Creative Writing"),
  PortFolioItem(title: "Creativity"),
  PortFolioItem(title: "Customer Service"),
  PortFolioItem(title: "Customer Support, CRM systems"),
  PortFolioItem(title: "Database query languages (SQL, etc)"),
  PortFolioItem(title: "Decision making"),
  PortFolioItem(title: "Design thinking"),
  PortFolioItem(title: "Domain name systems (DNS)"),
  PortFolioItem(title: "Email and internet"),
  PortFolioItem(title: "File management and data back-up"),
  PortFolioItem(title: "Graphical design tools"),
  PortFolioItem(title: "Mobile applications"),
  PortFolioItem(title: "Non-relational databases (NoSQL, etc)"),
  PortFolioItem(title: "Object oriented databases"),
  PortFolioItem(title: "Object oriented programming"),
  PortFolioItem(title: "Product management"),
  PortFolioItem(title: "Search engine optimization"),
  PortFolioItem(title: "Server hosting and management"),
  PortFolioItem(title: "Testing and debugging"),
  PortFolioItem(title: "User Experience and User Interface (UI/UX)"),
  PortFolioItem(title: "User management and administration"),
  PortFolioItem(title: "Web servers"),
  PortFolioItem(title: "Web service and application development"),
];